tomcat7::install::jdbc:                    "9.3-1101-jdbc4.jar"
tomcat7::install::jdbc_source:             "https://oss.sonatype.org/content/repositories/releases/org/postgresql/postgresql/9.3-1101-jdbc4/postgresql-9.3-1101-jdbc4.jar"
tomcat7::install::login:                   "loginModule.jar"
tomcat7::install::login_source:            "org.chtijbug.drools:drools-platform-login:0.5.1-SNAPSHOT:jar"
tomcat7::install::designer:                "designer.war"
tomcat7::install::designer_source:          "org.chtijbug.drools:drools-platform-designer:0.5.1-SNAPSHOT:war"
tomcat7::install::dbutils:                  "commons-dbutils.jar"
tomcat7::install::dbutils_source:           "http://central.maven.org/maven2/commons-dbutils/commons-dbutils/1.6/commons-dbutils-1.6.jar"
tomcat7::install::drools_guvnor:           "drools-guvnor.war"
tomcat7::install::drools_platform:         "drools-platform-ui.war"
tomcat7::install::drools_platform_source:  "org.chtijbug.drools:drools-platform-manager-ui:0.5.1-SNAPSHOT:war"
tomcat7::install::loyalty_soap:         	"loyalty-soap-server.war"
tomcat7::install::loyalty_soap_source:  	"org.chtijbug.drools:loyalty-soap-server:0.5.1-SNAPSHOT:war"
tomcat7::install::loyalty_web:         		"loyalty-web.war"
tomcat7::install::loyalty_web_source:  		"org.chtijbug.drools:loyalty-web:1.0.0-SNAPSHOT:war"
tomcat7::install::swimming_pool:         	"swimming-pool-soap-server.war"
tomcat7::install::swimming_pool_source:  	"org.chtijbug.drools:swimming-pool-soap-server:0.5.1-SNAPSHOT:war"



pgsqldpf::install::guvnor:               "guvnor"
pgsqldpf::install::guvnor_psswd:         "guvnor"
pgsqldpf::install::security_db:          "security"
pgsqldpf::install::security_user:        "security"
pgsqldpf::install::security_password:    "security"
tomcat7::install::guvnor_source:           "org.chtijbug.drools:drools-platform-brms:0.5.1-SNAPSHOT:war"
pgsqldpf::install::platform:             "platform"
pgsqldpf::install::platform_psswd:       "platform"
pgsqldpf::install::tablespacedir:        "/var/lib/postgresql/9.3/myspace/"
pgsqldpf::install::loyalty_user:             "loyaltyweb"
pgsqldpf::install::loyalty_passwd:       "loyaltyweb"
